# Normal profile
limit_req zone=global_www_normal burst=30 nodelay;

location /auth/login {
    limit_req zone=auth_login_normal burst=8 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}

location /api/ {
    limit_req zone=global_api_normal burst=20 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}
