# Elevated profile
limit_req zone=global_www_elevated burst=40 nodelay;

location /auth/login {
    limit_req zone=auth_login_elevated burst=8 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}

location /api/ {
    limit_req zone=global_api_elevated burst=18 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}
