# Under attack profile
limit_req zone=global_www_under_attack burst=20 nodelay;

location /auth/login {
    limit_req zone=auth_login_under_attack burst=4 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}

location ~* ^/api/client/servers/[a-f0-9-]+/(resources|websocket)$ {
    limit_req zone=global_api_under_attack burst=180 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}

location /api/ {
    limit_req zone=global_api_under_attack burst=40 nodelay;
    try_files $uri $uri/ /index.php?$query_string;
}
